steps:
- commands:
  - uuidgen > bazel_invocation_id
  - >
    bazel build //... 
    --invocation_id=$(cat bazel_invocation_id)
    --bes_backend=grpcs://bes.stg.flare.build 
    --bes_results_url="https://dashboard.stg.flare.build/#/invocations/"
  - >
    echo "[Invocation $(cat bazel_invocation_id)](https://dashboard.stg.flare.build/#/invocations/$(cat bazel_invocation_id))"
    | buildkite-agent annotate --style 'success'
  agents:
    queue: default

